name: test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
  check:
    strategy:
      fail-fast: true

    name: GUni
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: |
          yarn install
        shell: bash

      - name: Run lint check
        run: pnpm run lint:check

      - name: Build Solidity Contracts
        run: |
          yarn compile
        id: build

      - name: Run Tests
        run: |
          yarn test
        id: test
