name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: true

    name: GUni
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: |
          yarn install
        shell: bash

      - name: Run lint check
        run: yarn run format:check

      - name: Build Solidity Contracts
        run: |
          yarn run compile
        env:
          # Dummy value, obviously
          DEPLOYER_PRIVATE_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
          ANVIL_PRIVATE_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
        id: build

      - name: Run Tests
        run: |
          yarn run test
        env:
          # Dummy value, obviously
          DEPLOYER_PRIVATE_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
          ANVIL_PRIVATE_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
        id: test
